In [1]:
import pandas as pd

In [2]:
#header = None toremove header
dataset = pd.read_csv(r"E:\STUDIES\data science\ML\SpamClassifier-master\SpamClassifier-master\smsspamcollection\SMSSpamCollection", sep = '\t', header = None)

In [4]:
dataset

0                                                  1
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
#Data cleaning and text preprocessing

In [6]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Asus\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [8]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [9]:
corpus = []
for i in range (0, len(dataset)):
    review = re.sub('[^a-zA-Z0-9]',' ', dataset[1][i])
    review = review.lower()
    review = review.split() 
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [16]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [10]:
#creating BOW of TF-IDF

In [11]:
#independent and dependent features
#dependent feature is spam
#independent feature is the corpus 

In [14]:
y = pd.get_dummies(dataset[0], drop_first = True)

In [15]:
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [23]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(corpus,y, test_size = 0.2,random_state = 0)

In [24]:
X_train

['good movi ok leav hourish',
 'free give otherwis nalla adi entey nattil kittum',
 'emigr someth ok mayb 5 30 bit hope',
 'got home babe still awak',
 'kay sinc alreadi',
 'workin get job',
 'said matter mind say matter',
 'oh yeah diet flew window',
 'sorri got thing may pub later',
 'ill call even ill idea',
 'dear reach room',
 'got look scrumptiou daddi want eat night long',
 'badrith chennai sure pick us competit',
 'da car park',
 'okay soon best',
 'yar els thk sort funni thing',
 'yup izzit still rain heavili co e mrt c outsid',
 'way ur home',
 'ok pop ask bout someth said around tonght wen girl come',
 'talk g x',
 'cool tyler take gonna buy drop place later tonight total order quarter got enough',
 '5 2 work time',
 'yup free',
 'mayb westshor hyde park villag place near hous',
 'said would woke',
 'drama pl enough famili struggl hot sun strang place reason ego go invit actual necess go wait seriou reppurcuss',
 'what come hill monster hope great day thing r go fine busi th

In [25]:
dataset[0].value_counts()

ham     4825
spam     747
Name: 0, dtype: int64

In [26]:
##create BOW
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train = cv.fit_transform(X_train).toarray()

In [27]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
X_test = cv.transform(X_test).toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [30]:
cv.vocabulary_

{'good': 948,
 'movi': 1459,
 'ok': 1560,
 'leav': 1230,
 'free': 847,
 'give': 915,
 'otherwis': 1599,
 'someth': 1986,
 'mayb': 1372,
 '30': 92,
 'bit': 338,
 'hope': 1071,
 'got': 963,
 'home': 1068,
 'babe': 293,
 'still': 2035,
 'awak': 283,
 'sinc': 1948,
 'alreadi': 215,
 'workin': 2453,
 'get': 900,
 'job': 1156,
 'said': 1848,
 'matter': 1365,
 'mind': 1404,
 'say': 1863,
 'oh': 1557,
 'yeah': 2483,
 'diet': 665,
 'oh yeah': 1559,
 'sorri': 1996,
 'thing': 2144,
 'may': 1371,
 'pub': 1736,
 'later': 1211,
 'ill': 1106,
 'call': 401,
 'even': 754,
 'idea': 1100,
 'dear': 638,
 'reach': 1763,
 'room': 1831,
 'look': 1287,
 'daddi': 618,
 'want': 2366,
 'eat': 720,
 'night': 1519,
 'long': 1284,
 'chennai': 481,
 'sure': 2079,
 'pick': 1647,
 'us': 2315,
 'competit': 538,
 'da': 615,
 'car': 438,
 'park': 1613,
 'da car': 616,
 'okay': 1571,
 'soon': 1993,
 'best': 326,
 'yar': 2480,
 'els': 729,
 'thk': 2152,
 'sort': 2000,
 'funni': 882,
 'yup': 2498,
 'izzit': 1147,
 'rain': 1

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier().fit(X_train,y_train)

C:\Users\Asus\AppData\Local\Temp/ipykernel_15788/1946748256.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  classifier=RandomForestClassifier().fit(X_train,y_train)


In [31]:
y_pred=classifier.predict(X_test)

In [32]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [33]:
accuracy_score(y_test,y_pred)

0.9856502242152466

In [34]:
confusion_matrix(y_test,y_pred)

array([[955,   0],
       [ 16, 144]], dtype=int64)

# News classificaton project


In [3]:
import tarfile
import numpy as np
from six.moves import urllib
import pandas as pd
import os,sys

In [2]:
pip install kaggle

  Created wheel for kaggle: filename=kaggle-1.5.12-py3-none-any.whl size=73051 sha256=114df82d7f396e5c0dbad93d33ae6bdc9211f0fe364d90b9e732819a6af727cd
  Stored in directory: c:\users\asus\appdata\local\pip\cache\wheels\ac\b2\c3\fa4706d469b5879105991d1c8be9a3c2ef329ba9fe2ce5085e
Successfully built kaggle
Note: you may need to restart the kernel to use updated packages.


In [4]:
os.getcwd()

'E:\\STUDIES\\data science'

In [6]:
raw_data_dir= "zip_file"
os.makedirs(raw_data_dir,exist_ok=True)

In [2]:
! mkdir ~\.kaggle

In [ ]:
os.makedirs(tgz_download_dir,exist_ok=True)

In [12]:
!kaggle competitions download -c learn-ai-bbc

  0%|          | 0.00/1.85M [00:00<?, ?B/s]
 54%|#####4    | 1.00M/1.85M [00:00<00:00, 4.80MB/s]
100%|##########| 1.85M/1.85M [00:00<00:00, 4.56MB/s]
100%|##########| 1.85M/1.85M [00:00<00:00, 4.60MB/s]


In [11]:
!kaggle competitions download -c learn-ai-bbc -f $"BBC News Train.csv" -p $raw_data_dir --force

404 - Not Found


In [5]:
copy kaggle.json~\kaggle\

kaggle.json~\kaggle\* 

The system cannot find the path specified.



        0 file(s) copied.


In [7]:
def download_housing_data(self,) -> str:
    try:
        # remote url to download dataset
        download_url = 

        #folder location to download file
        raw_data_dir = self.data_ingestion_config.raw_data_dir

        #if os.path.exists(raw_data_dir):
            #os.remove(raw_data_dir)

        os.makedirs(raw_data_dir,exist_ok=True)

        banking_file_name = 'FRAUD'

        raw_data_file_path = os.path.join(raw_data_dir, banking_file_name)

        logging.info(f"Downloading file from :[{download_url}] into :[{raw_data_file_path}]")
        urllib.request.urlretrieve(download_url, raw_data_file_path)
        logging.info(f"File :[{raw_data_file_path}] has been downloaded successfully.")
        return raw_data_file_path



SyntaxError: invalid syntax (Temp/ipykernel_10412/1999584653.py, line 4)