<a href="https://colab.research.google.com/github/AAKAAASSHHH24/NLP-BASICS/blob/main/Text_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# Bag of words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch FOOTBALL",
                         "FOOTBALLERS watch FOOTBALL",
                         "FANS LOVE FOOTBALLERS",
                          "FANS TRAVEL"],"output":[1,1,0,0]})

df

text  output
0       people watch FOOTBALL       1
1  FOOTBALLERS watch FOOTBALL       1
2       FANS LOVE FOOTBALLERS       0
3                 FANS TRAVEL       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [5]:
#vocabulary
print(cv.vocabulary_)

{'people': 4, 'watch': 6, 'football': 1, 'footballers': 2, 'fans': 0, 'love': 3, 'travel': 5}


In [6]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 0 0 1 0 1]]
[[0 1 1 0 0 0 1]]
[[1 0 1 1 0 0 0]]


In [9]:
# new
cv.transform(['FANS LOVE TO WATCH FOOTBALLERS PLAY FOOTBALL']).toarray()

array([[1, 1, 1, 1, 0, 0, 1]])

#  N-grams

In [10]:
df = pd.DataFrame({"text":["people watch FOOTBALL",
                         "FOOTBALLERS watch FOOTBALL",
                         "FANS LOVE FOOTBALLERS",
                          "FANS TRAVEL"],"output":[1,1,0,0]})

df

text  output
0       people watch FOOTBALL       1
1  FOOTBALLERS watch FOOTBALL       1
2       FANS LOVE FOOTBALLERS       0
3                 FANS TRAVEL       0

In [11]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [12]:
bow = cv.fit_transform(df['text'])

In [13]:
print(cv.vocabulary_)

{'people watch': 4, 'watch football': 5, 'footballers watch': 2, 'fans love': 0, 'love footballers': 3, 'fans travel': 1}


In [14]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 0 0 1 1]]
[[0 0 1 0 0 1]]
[[1 0 0 1 0 0]]


# TF-IDF (Term frequency- Inverse document frequency)

In [19]:
"""What is TF (term frequency)?

Term frequency works by looking at the frequency of a particular term you are concerned with relative to the document. 
There are multiple measures, or ways, of defining frequency:

Number of times the word appears in a document (raw count).
Term frequency adjusted for the length of the document (raw count of occurences divided by number of words in the document).
Logarithmically scaled frequency (e.g. log(1 + raw count)).
Boolean frequency (e.g. 1 if the term occurs, or 0 if the term does not occur, in the document)."""

'What is TF (term frequency)?\n\nTerm frequency works by looking at the frequency of a particular term you are concerned with relative to the document. \nThere are multiple measures, or ways, of defining frequency:\n\nNumber of times the word appears in a document (raw count).\nTerm frequency adjusted for the length of the document (raw count of occurences divided by number of words in the document).\nLogarithmically scaled frequency (e.g. log(1 + raw count)).\nBoolean frequency (e.g. 1 if the term occurs, or 0 if the term does not occur, in the document).'

In [20]:
"""What is IDF (inverse document frequency)?

Inverse document frequency looks at how common (or uncommon) a word is amongst the corpus. 
IDF is calculated as follows where t is the term (word) we are looking to measure the commonness of and N is the number of documents (d) in the corpus (D).. 
The denominator is simply the number of documents in which the term, t, appears in."""

'What is IDF (inverse document frequency)?\n\nInverse document frequency looks at how common (or uncommon) a word is amongst the corpus. \nIDF is calculated as follows where t is the term (word) we are looking to measure the commonness of and N is the number of documents (d) in the corpus (D).. \nThe denominator is simply the number of documents in which the term, t, appears in.'

In [16]:
df = pd.DataFrame({"text":["people watch FOOTBALL",
                         "FOOTBALLERS watch FOOTBALL",
                         "FANS LOVE FOOTBALLERS",
                          "FANS TRAVEL"],"output":[1,1,0,0]})

df

text  output
0       people watch FOOTBALL       1
1  FOOTBALLERS watch FOOTBALL       1
2       FANS LOVE FOOTBALLERS       0
3                 FANS TRAVEL       0

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [18]:
tfid.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.        , 0.        , 0.66767854,
        0.        , 0.52640543],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.        ,
        0.        , 0.57735027],
       [0.52640543, 0.        , 0.52640543, 0.66767854, 0.        ,
        0.        , 0.        ],
       [0.6191303 , 0.        , 0.        , 0.        , 0.        ,
        0.78528828, 0.        ]])

In [21]:
print(tfid.idf_)

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.51082562]


In [23]:
print(tfid.get_feature_names_out())

['fans' 'football' 'footballers' 'love' 'people' 'travel' 'watch']
